services:
  movistar_u7d:
  # build:
  #   context: .
  #   args:
  #     BUILD_TYPE: full
  #     BUILDKIT_INLINE_CACHE: 1
  #     DOCKER_BUILDKIT: 1
  #     COMPOSE_DOCKER_CLI_BUILD: 1
  # image: registry.marcet.info/javier/movistar-u7d:latest
  # image: registry.marcet.info/javier/movistar-u7d:stable
  # image: registry.marcet.info/javier/movistar-u7d:stable-slim
    image: registry.marcet.info/javier/movistar-u7d:unstable
  # image: registry.marcet.info/javier/movistar-u7d:unstable-slim
    container_name: movistar_u7d
    cap_add:
      - NET_ADMIN
      - NET_BROADCAST
      - SYS_ADMIN
      - SYS_NICE
    dns: 172.26.23.3
    dns_search: ""
    environment:
      - LAN_IP
    restart: ${RESTART_POLICY}
    network_mode: host
  # devices:
  #   - /dev/dri:/dev/dri
    volumes:
      - /etc/localtime:/etc/localtime
  #   - ./:/app
  #   - ${RECORDINGS}:${RECORDINGS}
  #   - ${RECORDINGS_TMP}:${RECORDINGS_TMP}
      - ${U7D_HOME}:/home
  # cpu_shares: 8192
  # cpus: 4
  # mem_limit: 4gb
  # memswap_limit: 4gb
  # healthcheck:
  #   test: nc -zv $LAN_IP 8888
  #   interval: 10s
  #   timeout: 5s
  #   retries: 5

# vim: et ci pi sts=2 sw=2 ts=2
